version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: gianglt90/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-users
    image: gianglt90/udagram-api-users
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: gianglt90/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: gianglt90/udagram-frontend:local